server {
    listen 80;
    server_name localhost;

    # =========================
    # FRONTEND (HTML / CSS / JS)
    # =========================
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # =========================
    # API GATEWAY
    # =========================
    location /api/ {
        # REMOVE /api do path
        rewrite ^/api/(.*)$ /$1 break;

        proxy_pass http://api_gateway:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # =========================
    # EDGE HEALTH
    # =========================
    location /health {
        return 200 "EDGE OK\n";
        add_header Content-Type text/plain;
    }
}
